//! Shared MVT (Mapbox Vector Tile) protobuf types.
//!
//! Generated by `prost` from the upstream `vector_tile.proto` at build time.
//! Extracted here so both `stats::collect` and `prune` can share the same types.

include!(concat!(env!("OUT_DIR"), "/vector_tile.rs"));
