//! Typed visitor for paint/layout properties on generated layer structs.
//!
//! Unlike the JSON-based `StyleVisitor` (which walks `serde_json::Value` trees),
//! this visitor operates directly on the typed Rust structs, eliminating the
//! serialize→walk→deserialize round-trip for passes that can work with typed data.
//!
//! The `walk_typed_style_mut` function is generated by the code generator.

use crate::mir::MirPropertySection;
use crate::shared_expr::{ArrayPropInner, ColorExpression, FormattedPropInner, NumericExpression};
use crate::spec::{Boolean, String as SpecString, TypedLayer};

/// Context provided at each typed paint/layout property visit site.
pub struct TypedPropertyContext<'a> {
    pub layer_index: usize,
    pub layer_type: &'a str,
    pub section: MirPropertySection,
    pub property_name: &'a str,
}

/// Visitor trait for typed style tree walks.
///
/// All methods have default no-op implementations; implement only what you need.
///
/// Call order per layer: `visit_filter` → `visit_numeric` / `visit_color` /
/// `visit_boolean_prop` / `visit_string` / `visit_formatted` / `visit_array`
/// (for each present expression-backed paint/layout property) → `visit_layer`.
pub trait TypedStyleVisitor {
    /// Called for each expression-backed numeric property (mutable).
    fn visit_numeric(&mut self, ctx: &TypedPropertyContext<'_>, expr: &mut NumericExpression) {
        let _ = (ctx, expr);
    }

    /// Called for each expression-backed color property (mutable).
    fn visit_color(&mut self, ctx: &TypedPropertyContext<'_>, expr: &mut ColorExpression) {
        let _ = (ctx, expr);
    }

    /// Called for each expression-backed boolean property (mutable).
    fn visit_boolean_prop(&mut self, ctx: &TypedPropertyContext<'_>, expr: &mut Boolean) {
        let _ = (ctx, expr);
    }

    /// Called for each expression-backed string property (mutable).
    fn visit_string(&mut self, ctx: &TypedPropertyContext<'_>, expr: &mut SpecString) {
        let _ = (ctx, expr);
    }

    /// Called for each expression-backed formatted text property (mutable).
    fn visit_formatted(&mut self, ctx: &TypedPropertyContext<'_>, expr: &mut FormattedPropInner) {
        let _ = (ctx, expr);
    }

    /// Called for each expression-backed array property (mutable).
    fn visit_array(&mut self, ctx: &TypedPropertyContext<'_>, expr: &mut ArrayPropInner) {
        let _ = (ctx, expr);
    }

    /// Called for each layer's `filter` expression (mutable).
    fn visit_filter(&mut self, layer_index: usize, layer_type: &str, filter: &mut Boolean) {
        let _ = (layer_index, layer_type, filter);
    }

    /// Called for each typed layer (mutable), after filter and properties.
    fn visit_layer(&mut self, layer_index: usize, layer_type: &str, layer: &mut TypedLayer) {
        let _ = (layer_index, layer_type, layer);
    }
}
